### ISSUE TITLE
no way to initialize the modal outside of modal context

### ISSUE THREAD

**Issue by abhij89** [faceless-ui/modal#31]
I am trying to integrate the modal with the slider but it is unable to toggle the modal if the slider is outside of the modal container. Is there a way to toggle the modal on the click of the slider image?

**Comment by jacobsfletch** [comment]
Hi @abhij89! This is totally possible and something I do often. As long as the `ModalProvider` wraps your app, including your slider, you should be able to toggle it open using the `open('your-slug')` method. Let me know if this helps. If not,  send in a snippet or two of your code and I can help further debug.

**Comment by abhij89** [comment]
Great thank you, that helped. Please consider adding this to the documentation.
