### ISSUE TITLE
Modal not fully trapping focus

### ISSUE THREAD

**Issue by andykimchris** [faceless-ui/modal#37]
Hey Faceless-UI Team, quick question(which might end up being an issue) does the modal inherently trap the entire focus within the modal?

While tabbing through a simple implementation, the focus switches out of the modal into my navbar. Is this the initial setting of the modal?

I can't share the current implementation as it's a client project, but the general idea is the focus leaves the modal and goes to the navbar links. Any clarity on this will be much appreciated

**Comment by jacobsfletch** [comment]
Hi @andykimchris! Focus should not return back to your root document until the modal has closed. What version are you running? Focus trap appears to be working as expected in the latest version, which you can see in one of the examples on the website [here](http://localhost:3000/docs/modal/examples/lightbox). [CodeSandbox](https://codesandbox.io/) is a great place to recreate and isolate your issue. If can whip something together and share it with me, I'd be happy to publish a patch version for you. We'll get to the bottom of it either way.

**Comment by andykimchris** [comment]
Hello @jacobsfletch thanks for the reply. I upgraded to the latest version, and you're right it locks focus within the modal. Thank you for replying back to me. I was using version 1.3.0.
