### ISSUE TITLE
Seeking help toggling burger using isModalOpen

### ISSUE THREAD

**Issue by ballermatic** [faceless-ui/modal#47]
Nextjs/Typescript novice here. I have a mobile menu using America's Favorite Modal (awesome!) however, I cannot sort out how to access the modal state "isOpen" from a sibling component. I am using [Hamburger React](https://github.com/luukdv/hamburger-react)

Everything is working great except I need to toggle the burger when  

Here's what I have so far…
```
const MenuMobile = () => {
  return (
    <>
      <ModalToggler
        slug='menuMobile'
        className={styles.burger}>
        <Hamburger
          color='var(--light)'
          duration={0.25}
          label='Show menu'
          size={28}
          rounded
          // Todo: toggle burger on menu item click - use isModalOpen?
          // toggled={isOpen} toggle={setOpen}
        />
      </ModalToggler>
      <Modal slug='menuMobile'>
        <nav className={styles.menuMobile}>
          <ul>
            <li className={styles.menuItem}>
              <ModalToggler slug='menuMobile'>
                <Link href='/how-it-works'>How It Works</Link>
              </ModalToggler>
            </li>
etc.
```

**Comment by jacobsfletch** [comment]
@ballermatic you can call the `useModal()` hook and read from `modalState`, like this:

```ts
const { modalState } = useModal()
const isOpen = modalState.menuMobile?.isOpen
```

Let me know if this works for you!

**Comment by ballermatic** [comment]
That worked! I knew it was something obvious but couldn't figure it out. Thanks!

**Comment by jacobsfletch** [comment]
Niiice! Happy to help.
